### ISSUE TITLE
Oxygen molecules lose all rotational energy when switching between molecules

### ISSUE THREAD

**Issue by bryo5363** [phetsims/states-of-matter#28] opened 2015-02-03 17:33 UTC
Test device: MacBook Pro

Operating System: OSX 10.10.1

Browser: Safari 8.0 (10600.1.25.1)

Problem description: When switching between molecules in the Phase Changes tab, I noticed that oxygen lost all of its rotational energy while all other molecules retained their motion. 

Steps to reproduce:
-open sim
-open phase changes tab
-select oxygen
-select another molecule
-go back to oxygen. Notice most of the molecules did not retain their rotational energy. 
Severity:

Screenshots:

Troubleshooting information (do not edit):
Name: States of Matter
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.2/states-of-matter_en.html
Version: 1.0.0-dev.2
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.1.25 (KHTML, like Gecko) Version/8.0 Safari/600.1.25
Language: en-us
Window: 1240x647
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-10.0.19)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by notsiddhartha** [comment] 2015-02-13 14:56
moleculeForce and moleculeTorque are becoming zero after switching back. Need to investigate further.

**Comment by notsiddhartha** [comment] 2015-02-16 14:51
We observed that the temperature scale factor is turning out to be a small value. The rotation rates are multiplied by the scale factor and we are running the thermostat 8 times per dt. As a result rotation rates are turning out to be pretty small after switching to Oxygen from a different molecule.

@jbphet, what do you think of the above?

**Comment by jbphet** [comment] 2015-02-25 00:08
There is still something a bit odd about switching to oxygen when it is in a gaseous state.  I've just switched back and forth a bunch of times using the current master version, and it's hard to describe exactly what the issue is, but it appears to be that the energy is not very evenly distributed between the molecules.  There are a handful that are moving very quickly, and quite a few that aren't moving at all.  This energy quickly evens out, but it still looks quite odd.  So, bottom line is that I think this needs a bit more scrutiny.

If the assignee thinks that this is a separate issue from the original report, please feel free to break it out into another GitHub issue.

**Comment by ChandrashekarBemagoni** [comment] 2015-05-11 13:41
Fixed in above commit.  Assigning to @bryo5363 for verification

**Comment by jbphet** [comment] 2015-05-15 22:29
Nicely done, it looks great now!  Closing.

**Closed by jbphet** 2015-05-15 22:29 UTC
