### ISSUE TITLE
State screen does not reflect force arrows

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/states-of-matter#283] opened 2020-05-18 22:37 UTC
<b>Test Device</b>

Windows 10

<b>Operating System</b>

Windows 10 1903

<b>Browser</b>

Firefox 76.0.1

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/501

This appears to be the result of the bug mentioned in https://github.com/phetsims/states-of-matter/issues/274. The state screen appears to reflect the correct position of the force arrows, while the original screen reflects the bugged arrow positions.

<b>Steps to Reproduce</b>

1. Select adjustable attraction
2. Select show repulsive and attractive force arrows
3. Pause simulation
4. Move atom closer to the fixed atom
5. Switch to argon atoms
6. Switch back to adjustable attraction atoms
7. Unpause simulation

<b>Visuals</b>

![2020-05-18StatesPhetiostatesArrows](https://user-images.githubusercontent.com/54685448/82266000-b3f15a00-9925-11ea-9e3c-3f0d19fa2d8a.gif)

</details>

**Comment by jbphet** [comment] 2020-05-29 21:27
@arouinfar and I reviewed this on 5/29/2020 and we decided that it does not need to be fixed for an early customer dev release (since the customer is not expected to use this screen), but it should be addressed before a fully phet-io release of this sim.

**Comment by jbphet** [comment] 2020-06-19 21:15
This is now fixed, see the description in https://github.com/phetsims/states-of-matter/issues/274#issuecomment-646862398.

@KatieWoe - please check on master.  If it looks good, go ahead and close, since it has the same root cause as #274 so we don't need to re-verify on the next release.

**Comment by KatieWoe** [comment] 2020-06-19 21:28
Looks good on master

**Closed by KatieWoe** 2020-06-19 21:28 UTC
Labels: type:bug
