### ISSUE TITLE
NaN for temperature reading when molecules added to empty container

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/states-of-matter#234] opened 2018-10-11 19:23 UTC
**Test Device**

Early 2015 MacBook Air

**Operating System**

macOS 10.14 (Seems to occur on all OS's.)

**Browser**

Safari 12.0 (Seems to occur on all browsers.)

**Problem Description**

For https://github.com/phetsims/QA/issues/205. See title and visuals.

<details>
<summary>1st Error</summary>

On Windows+Chrome:
```
Error: <rect> attribute y: Expected length, "NaN".
updateSVGSelf @ states-of-matter_en_phet.html:992
updateSVG @ states-of-matter_en_phet.html:992
update @ states-of-matter_en_phet.html:992
update @ states-of-matter_en_phet.html:992
update @ states-of-matter_en_phet.html:992
update @ states-of-matter_en_phet.html:992
update @ states-of-matter_en_phet.html:992
updateDisplay @ states-of-matter_en_phet.html:992
stepSimulation @ states-of-matter_en_phet.html:992
stepOneFrame @ states-of-matter_en_phet.html:992
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
```

On macOS+Safari:
```
[Error] Error: Invalid value for <rect> attribute y="NaN"
	updateSVGSelf (states-of-matter_en_phet.html:992:428741)
	updateSVG (states-of-matter_en_phet.html:992:157193)
	update (states-of-matter_en_phet.html:992:157129)
	update (states-of-matter_en_phet.html:992:897918)
	update (states-of-matter_en_phet.html:992:926780)
	update (states-of-matter_en_phet.html:992:888087)
	update (states-of-matter_en_phet.html:992:926780)
	updateDisplay (states-of-matter_en_phet.html:992:1000392)
	stepSimulation (states-of-matter_en_phet.html:992:1368455)
	stepOneFrame (states-of-matter_en_phet.html:992:1367549)
	runAnimationLoop (states-of-matter_en_phet.html:992:1367407)
	runAnimationLoop
```

</details>

<details>
<summary>2nd Error</summary>

On Windows+Chrome:
```
states-of-matter_en_phet.html:992 Error: <rect> attribute height: Expected length, "NaN".
updateSVGSelf @ states-of-matter_en_phet.html:992
updateSVG @ states-of-matter_en_phet.html:992
update @ states-of-matter_en_phet.html:992
update @ states-of-matter_en_phet.html:992
update @ states-of-matter_en_phet.html:992
update @ states-of-matter_en_phet.html:992
update @ states-of-matter_en_phet.html:992
updateDisplay @ states-of-matter_en_phet.html:992
stepSimulation @ states-of-matter_en_phet.html:992
stepOneFrame @ states-of-matter_en_phet.html:992
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
requestAnimationFrame (async)
runAnimationLoop @ states-of-matter_en_phet.html:992
```

On macOS+Safari:
```
[Error] Error: Invalid value for <rect> attribute y="NaN"
	updateSVGSelf (states-of-matter_en_phet.html:992:428741)
	updateSVG (states-of-matter_en_phet.html:992:157193)
	update (states-of-matter_en_phet.html:992:157129)
	update (states-of-matter_en_phet.html:992:897918)
	update (states-of-matter_en_phet.html:992:926780)
	update (states-of-matter_en_phet.html:992:888087)
	update (states-of-matter_en_phet.html:992:926780)
	updateDisplay (states-of-matter_en_phet.html:992:1000392)
	stepSimulation (states-of-matter_en_phet.html:992:1368455)
	stepOneFrame (states-of-matter_en_phet.html:992:1367549)
	runAnimationLoop (states-of-matter_en_phet.html:992:1367407)
	runAnimationLoop
```

</details>

---

**Steps to Reproduce**

These are the best steps to reproduce that I've found.

1. States screen.
2. Any molecule will work.
3. Get all of the molecules out of the container. (This requires patience.)
4. Make sure interaction strength is weak.
5. Pump molecules into container.
6. Move the lid down. The temperature reading should be "NaN K" or "NaN deg. C".

**Visuals**

![som_issue](https://user-images.githubusercontent.com/31285590/46825548-21540680-cd51-11e8-87df-672df2752012.png)

![som_issue](https://user-images.githubusercontent.com/31285590/46825529-16997180-cd51-11e8-93c6-0fa37a1cd0f0.gif)

<details>
<summary><b>Troubleshooting Information</b> </summary>

Name: ‪States of Matter‬
URL: https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-rc.2/phet/states-of-matter_en_phet.html
Version: 1.1.0-rc.2 2018-10-05 21:58:32 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15
Language: en-US
Window: 1440x837
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-12.0.34)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"d7ba44e2","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"bbbb514a","branch":"HEAD"},"dot":{"sha":"820111c8","branch":"HEAD"},"joist":{"sha":"fb860843","branch":"HEAD"},"kite":{"sha":"59755f7e","branch":"HEAD"},"nitroglycerin":{"sha":"ccaab9cd","branch":"HEAD"},"phet-core":{"sha":"68a89cc4","branch":"HEAD"},"phet-io":{"sha":"364077cf","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"abc4ae3e","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"429886e7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ef0b0b0c","branch":"HEAD"},"phet-io-wrappers":{"sha":"7ec1a04a","branch":"HEAD"},"phetcommon":{"sha":"22b158d0","branch":"HEAD"},"query-string-machine":{"sha":"c2e502fb","branch":"HEAD"},"scenery":{"sha":"415371c3","branch":"HEAD"},"scenery-phet":{"sha":"94b92879","branch":"HEAD"},"sherpa":{"sha":"a9fd066b","branch":"HEAD"},"states-of-matter":{"sha":"9796b83a","branch":"HEAD"},"sun":{"sha":"3086e97a","branch":"HEAD"},"tambo":{"sha":"0e5b9133","branch":"HEAD"},"tandem":{"sha":"a2348c0c","branch":"HEAD"}}
</details>

**Comment by ariel-phet** [comment] 2018-10-15 18:28
@lmulhall-phet can you see if this occurs on the published version?

**Comment by KatieWoe** [comment] 2018-10-15 19:59
@ariel-phet did a quick test on my own and at least initially it doesn't seem to occur in published.

**Comment by jbphet** [comment] 2018-10-23 22:12
There seem to be a couple of inconsistencies in the problem description.  First, the steps to reproduce say "States screen", but there is no pump on that screen, so I'm assuming it should say "Phase Changes screen".  Second, it says "Any molecule will work", but then later says "Make sure interaction strength is weak".  The interaction strength is only available when adjustable attraction is selected, and that appears to be the case in the screen captures.  @lmulhall-phet - can you please clarify?

**Comment by jbphet** [comment] 2018-10-26 17:32
This issue was due to a problem where the Verlet algorithm implementations were not handling the case where there were no particles in the container, and were returning `undefined`.  This has always been the behavior, but now that a moving average is used to keep track of temperature changes, the undefined value leads to negative consequences.  The implementations (there are three of them) now return the min allowable model temperature in the case of no particles.

**Comment by KatieWoe** [comment] 2018-10-26 19:02
1.1.0-rc.3 looks good on Win 10 chrome with argon.

**Comment by jbphet** [comment] 2018-10-29 23:10
Deployed in v1.1.0, closing.

**Closed by jbphet** 2018-10-29 23:10 UTC
Labels: status:fixed-awaiting-deploy, type:bug
