### ISSUE TITLE
sim relies on align:'right' default for Panels

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#146] opened 2016-08-25 23:41 UTC
Related to https://github.com/phetsims/sun/issues/252, this sim use Panel option `minWidth` and relies on the old default of `align:'right'`.  Below are the stack traces for occurrences that need to be checked. These are the occurrences noted when loading the sim in requirejs mode. If the sim creates Panels dynamically, you should do further checking with fuzzMouse.

```
Error
    at new Panel (http://localhost/~cmalley/GitHub/sun/js/Panel.js?bust=1472222581925:52:15)
    at new AtomicInteractionsControlPanel (http://localhost/~cmalley/GitHub/states-of-matter/js/atomic-interactions/view/AtomicInteractionsControlPanel.js?bust=1472222581925:386:28)
    at new AtomicInteractionsScreenView (http://localhost/~cmalley/GitHub/states-of-matter/js/atomic-interactions/view/AtomicInteractionsScreenView.js?bust=1472222581925:78:42)
    at AtomicInteractionsScreen.createView (http://localhost/~cmalley/GitHub/states-of-matter/js/atomic-interactions/AtomicInteractionsScreen.js?bust=1472222581925:32:34)
    at AtomicInteractionsScreen.initializeView (http://localhost/~cmalley/GitHub/joist/js/Screen.js?bust=1472222581925:134:25)
    at AtomicInteractionsScreen.initializeModelAndView (http://localhost/~cmalley/GitHub/joist/js/Screen.js?bust=1472222581925:151:12)
    at initializeScreen (http://localhost/~cmalley/GitHub/joist/js/Sim.js?bust=1472222581925:441:14)
    at Array.forEach (native)
    at new Sim (http://localhost/~cmalley/GitHub/joist/js/Sim.js?bust=1472222581925:439:13)
    at http://localhost/~cmalley/GitHub/states-of-matter/js/states-of-matter-main.js?bust=1472222581925:41:15
```

**Comment by pixelzoom** [comment] 2016-08-26 15:00
Visually inspected and compared to previous dev versions, I see no change.  @jbphet up to you whether you want to inspect further or close.

**Comment by jbphet** [comment] 2016-08-26 17:32
This is a duplicate of https://github.com/phetsims/atomic-interactions/issues/57, and the panel has been tested and everything looks good.  Closing.

**Closed by jbphet** 2016-08-26 17:32 UTC
