### ISSUE TITLE
CT running lint all task

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#241] opened 2019-01-24 00:11 UTC
```
states-of-matter : build : phet
Failure to grunt snapshot-1548283113732/states-of-matter:
Running "lint-all" task

Running "report-media" task
>> missing-file: states-of-matter/images/flame.png
>> missing-file: states-of-matter/images/ice-cube-stack.png
>> missing-file: states-of-matter/images/som-atomic-interactions-icon.png
Fatal error: There is an issue with the licenses for media types.


Approximately 1/23/2019, 3:38:33 PM
```

**Comment by pixelzoom** [comment] 2019-01-24 03:42
Duplicate of https://github.com/phetsims/atomic-interactions/issues/77, closing.

**Closed by pixelzoom** 2019-01-24 03:42 UTC
Labels: type:automated-testing
