### ISSUE TITLE
Avoid scenery calls when painting a canvas

### ISSUE THREAD

**Issue by samreid** [phetsims/states-of-matter#111] opened 2015-10-26 17:12 UTC
Discovered by automated fuzz tester:

```
states-of-matter
Uncaught Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at Display.extend.ensureNotPainting (http://localhost:8080/scenery/js/display/Display.js?bust=1445829228910:1026:17)
    at BackboneDrawable.inherit.markDirtyDrawable (http://localhost:8080/scenery/js/display/BackboneDrawable.js?bust=1445829228910:209:22)
    at SVGBlock.inherit.markDirty (http://localhost:8080/scenery/js/display/Drawable.js?bust=1445829228910:264:31)
    at SVGBlock.inherit.markDirtyGroup (http://localhost:8080/scenery/js/display/SVGBlock.js?bust=1445829228910:158:12)
    at SVGGroup.inherit.markDirty (http://localhost:8080/scenery/js/display/SVGGroup.js?bust=1445829228910:121:20)
    at SVGGroup.inherit.markVisibilityDirty (http://localhost:8080/scenery/js/display/SVGGroup.js?bust=1445829228910:153:14)
    at ArrowNode.axon.Events.trigger0 (http://localhost:8080/axon/js/Events.js?bust=1445829228910:280:29)
    at ArrowNode.extend.setVisible (http://localhost:8080/scenery/js/nodes/Node.js?bust=1445829228910:2351:14)
    at InteractionCanvasNode.inherit.paintCanvas (http://localhost:8080/states-of-matter/js/common/view/InteractionPotentialCanvasNode.js?bust=1445829228910:90:46)
states-of-matter
Uncaught Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at Display.extend.ensureNotPainting (http://localhost:8080/scenery/js/display/Display.js?bust=1445829228910:1026:17)
    at BackboneDrawable.inherit.markDirtyDrawable (http://localhost:8080/scenery/js/display/BackboneDrawable.js?bust=1445829228910:209:22)
    at SVGBlock.inherit.markDirty (http://localhost:8080/scenery/js/display/Drawable.js?bust=1445829228910:264:31)
    at SVGBlock.inherit.markDirtyGroup (http://localhost:8080/scenery/js/display/SVGBlock.js?bust=1445829228910:158:12)
    at SVGGroup.inherit.markDirty (http://localhost:8080/scenery/js/display/SVGGroup.js?bust=1445829228910:121:20)
    at SVGGroup.inherit.markVisibilityDirty (http://localhost:8080/scenery/js/display/SVGGroup.js?bust=1445829228910:153:14)
    at HighlightNode.axon.Events.trigger0 (http://localhost:8080/axon/js/Events.js?bust=1445829228910:280:29)
    at HighlightNode.extend.setVisible (http://localhost:8080/scenery/js/nodes/Node.js?bust=1445829228910:2351:14)
    at HighlightNode.visible (http://localhost:8080/scenery/js/nodes/Node.js?bust=1445829228910:2355:33)
states-of-matter
Uncaught Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at Display.extend.ensureNotPainting (http://localhost:8080/scenery/js/display/Display.js?bust=1445829228910:1026:17)
    at CanvasBlock.inherit.markDirtyDrawable (http://localhost:8080/scenery/js/display/CanvasBlock.js?bust=1445829228910:196:22)
    at CanvasNodeDrawable.inherit.markDirty (http://localhost:8080/scenery/js/display/Drawable.js?bust=1445829228910:264:31)
    at ParticleCanvasNode.inherit.invalidatePaint (http://localhost:8080/scenery/js/nodes/CanvasNode.js?bust=1445829228910:66:30)
    at ParticleCanvasNode.inherit.step (http://localhost:8080/states-of-matter/js/common/view/ParticleCanvasNode.js?bust=1445829228910:85:12)
    at PhaseChangesScreenView.inherit.step (http://localhost:8080/states-of-matter/js/phase-changes/view/PhaseChangesScreenView.js?bust=1445829228910:269:27)
    at Sim.inherit.stepSimulation (http://localhost:8080/joist/js/Sim.js?bust=1445829228910:738:25)
    at Sim.inherit.runAnimationLoop (http://localhost:8080/joist/js/Sim.js?bust=144582922891
```

**Comment by jbphet** [comment] 2015-10-28 19:08
This is essentially a duplicate of #110.

**Comment by jbphet** [comment] 2015-10-28 20:43
This issue has been addressed by moving the updates of non-canvas nodes out of the paintCanvas call in InteractionPotentialCanvasNode.  Fuzz testing is now succeeding.  Closing.

**Closed by jbphet** 2015-10-28 20:43 UTC
