### ISSUE TITLE
Single molecule at 0K drifts left and right, can't be heated

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#192] opened 2016-12-12 21:23 UTC
I took a gander and the current state of this sim and I want to point out to @jbphet that, at 0K, with only one molecule in the container, a molecule will tend to drift left and right. The setup for this bug would simply involve reaching a state with only one molecule in the container, then cooling to 0K:

![som07](https://cloud.githubusercontent.com/assets/5863899/21117224/0320fc5c-c076-11e6-8a20-59538ee19299.gif)

Heating at this point does nothing to the molecule. This is not specific to water. Seen on iPad Air 2 iOS 9.3.5. EDIT: phetsims/tasks/issues/753

**Comment by jbphet** [comment] 2016-12-13 17:08
I've investigated this, and the issue is that there is some code in the isokinetic thermostat that doesn't scale down the particle velocity for falling particles.  This is done so that the particles will fall to the bottom of the container as the system approaches absolute zero.  In this particular case, the way that the forces and motion are updated just happens to make it such that the particle is always bouncing a tiny bit due to gravitational acceleration, and just happens to have a very small negative Y velocity when the thermostat is run.  This means that its velocity never gets scaled, neither up nor down.

I tried having a threshold of height in the isokinetic thermostat below which the velocity is always scaled regardless of whether the particle is falling, and this solved the problem described here, but introduced other odd looking behaviors.

I also tried adding a clause that only skips the scaling if the velocity is being scaled down.  This solved the problem of not being able to heat the particle back up, but I am very reluctant to add something like this just before doing a release candidate.

I propose that I move forward with the RC and leave this issue open, and will investigate it in parallel with the testing.  If a simple fix is found, it can be propagated to the RC branch.

**Comment by jbphet** [comment] 2016-12-16 23:55
The easiest - and perhaps the most practical - thing to do would be to eliminate the ability to get the particles to absolute zero.  This feature creates a number of problems, and there is already a lot of special case code to support it, and handling the case described in this issue would likely involve even more special-case code.  If I can't come up with anything elegant, and we decide that this issue should be addressed, I would advocate for the elimination of support for absolute zero.

**Comment by ariel-phet** [comment] 2016-12-17 02:20
@jbphet I think eliminating absolute zero would be fine (since it is unphysical). You could go to 1K or perhaps let it go to 0.1K and then things will be very slow, but it gets no colder, I would be completely fine with that.

**Comment by ariel-phet** [comment] 2016-12-20 16:55
Deferring to see if we get any emails to phethelp after publication

**Comment by jbphet** [comment] 2018-08-02 20:42
We've decided that this is an edge case.  Closing.

**Closed by jbphet** 2018-08-02 20:42 UTC
Labels: priority:5-deferred, type:bug

**Comment by KatieWoe** [comment] 2018-08-10 22:28
For phetsims/QA/issues/164
The movement at 0 K can happen with large numbers of particles as well, though heating can occur just fine.

**Comment by lmulhall-phet** [comment] 2018-10-26 21:49
Still an issue for https://github.com/phetsims/QA/issues/212. @jbphet will add some edge case code if someone complains about it.

**Comment by KatieWoe** [comment] 2018-10-26 21:56
To be clear, they can be heated.  The movement is the issue that is still present.
