### ISSUE TITLE
Pressure sometimes doesn't change when the lid is compressing

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#354] opened 2021-05-19 21:58 UTC
This is in the published sim! (1.2.1) But also, the version of this sim we are asked to test in phetsims/QA/issues/649 (https://phet-dev.colorado.edu/html/states-of-matter/1.2.2-rc.2/phet/states-of-matter_en_phet.html) no longer "produces" any change in pressure when collapsing the lid. It happens in both phet and phet-io brands. At least the Studio, Mirror Inputs, and State wrappers are buggy, but I don't see why not all of them would be buggy. There are times where this bug seems inconsistent, and if the bug doesn't occur it may help to refresh the web page and try again.

1. Go to https://phet-dev.colorado.edu/html/states-of-matter/1.2.2-rc.2/phet/states-of-matter_en_phet.html
2. Go to the second screen
3. Drag the lid down all the way and notice sometimes the pressure gauge does not increase.

![StOfMa](https://user-images.githubusercontent.com/5863899/118888242-a2d08580-b8b8-11eb-8cf7-e15452ecd6b9.gif)

Seen on Win 10 Chrome.

**Comment by KatieWoe** [comment] 2021-05-19 22:02
May have something to due with platform (somehow) since I have not been able to recreate on my device. Win 10 Chrome. @phet-steele what were you on?

**Comment by phet-steele** [comment] 2021-05-19 22:07
When trying to drag the lid in master, I immediately see this error.

```
Uncaught Error: Assertion failed: no space left in moving time window
    at window.assertions.assertFunction (assert.js:25)
    at TimeSpanDataQueue.add (TimeSpanDataQueue.js:51)
    at MonatomicVerletAlgorithm.updatePressure (AbstractVerletAlgorithm.js:283)
    at MonatomicVerletAlgorithm.updateMoleculePositions (AbstractVerletAlgorithm.js:187)
    at MonatomicVerletAlgorithm.updateForcesAndMotion (AbstractVerletAlgorithm.js:201)
    at PhaseChangesModel.stepInTime (MultipleParticleModel.js:845)
    at PhaseChangesModel.step (MultipleParticleModel.js:940)
    at Sim.js:287
    at Action.execute (Action.js:227)
    at Sim.stepSimulation (Sim.js:1064)
```

**Comment by jbphet** [comment] 2021-05-20 22:07
I've added some debug code on master to try to help track this down.

@phet-steele - Can you please reproduce this on your system using master and capture the output on the console?  It will be long, so I'd recommend putting it in a "details" section.

Also, is there any change the system you're testing with is using a faster-than-normal frame rate for the browser?  If so, that would explain the problem.

**Comment by jbphet** [comment] 2021-05-20 22:10
Note to self: It's a little lame that `TimeSpanDataQueue` requires the client to specify both the length of the queue and the expected dt.  Also, it shouldn't be called the "nominal" dt, it should be called the expected minimum.  I should modify these things as part of the overall fix for this.

**Comment by phet-steele** [comment] 2021-05-20 22:23
> Also, is there any change the system you're testing with is using a faster-than-normal frame rate for the browser? If so, that would explain the problem.

Almost guaranteed! `?profiler` has me running at 300 fps, which is expected on my device.

<details>
<summary>Output</summary>

=======
TimeSpanDataQueue.js:55 this.length = 793
TimeSpanDataQueue.js:56 this.maxTimeSpan = 12 seconds
TimeSpanDataQueue.js:57 this.head = 792
TimeSpanDataQueue.js:58 this.tail = 0
TimeSpanDataQueue.js:59 data queue contents:
TimeSpanDataQueue.js:69 -------
TimeSpanDataQueue.js:70   index: 791
TimeSpanDataQueue.js:71   dt:    0.016
TimeSpanDataQueue.js:72   value: 0
TimeSpanDataQueue.js:69 -------
TimeSpanDataQueue.js:70   index: 790
TimeSpanDataQueue.js:71   dt:    0.012
TimeSpanDataQueue.js:72   value: 0
TimeSpanDataQueue.js:69 -------
TimeSpanDataQueue.js:70   index: 789
TimeSpanDataQueue.js:71   dt:    0.012
TimeSpanDataQueue.js:72   value: 0
TimeSpanDataQueue.js:69 -------
TimeSpanDataQueue.js:70   index: 788
TimeSpanDataQueue.js:71   dt:    0.016
TimeSpanDataQueue.js:72   value: 0
TimeSpanDataQueue.js:69 -------
TimeSpanDataQueue.js:70   index: 787
TimeSpanDataQueue.js:71   dt:    0.012
TimeSpanDataQueue.js:72   value: 0
TimeSpanDataQueue.js:69 -------
TimeSpanDataQueue.js:70   index: 786
TimeSpanDataQueue.js:71   dt:    0.012
TimeSpanDataQueue.js:72   value: 0
TimeSpanDataQueue.js:69 -------
TimeSpanDataQueue.js:70   index: 785
TimeSpanDataQueue.js:71   dt:    0.016
TimeSpanDataQueue.js:72   value: 0
TimeSpanDataQueue.js:69 -------
TimeSpanDataQueue.js:70   index: 784
TimeSpanDataQueue.js:71   dt:    0.012
TimeSpanDataQueue.js:72   value: 0
TimeSpanDataQueue.js:69 -------
TimeSpanDataQueue.js:70   index: 783
TimeSpanDataQueue.js:71   dt:    0.012
TimeSpanDataQueue.js:72   value: 0
TimeSpanDataQueue.js:69 -------
TimeSpanDataQueue.js:70   index: 782
TimeSpanDataQueue.js:71   dt:    0.016
TimeSpanDataQueue.js:72   value: 0
TimeSpanDataQueue.js:69 -------
TimeSpanDataQueue.js:70   index: 781
TimeSpanDataQueue.js:71   dt:    0.012
TimeSpanDataQueue.js:72   value: 0
TimeSpanDataQueue.js:69 -------
TimeSpanDataQueue.js:70   index: 780
TimeSpanDataQueue.js:71   dt:    0.012
TimeSpanDataQueue.js:72   value: 0
TimeSpanDataQueue.js:69 -------
TimeSpanDataQueue.js:70   index: 779
TimeSpanDataQueue.js:71   dt:    0.016
TimeSpanDataQueue.js:72   value: 0
TimeSpanDataQueue.js:69 -------
TimeSpanDataQueue.js:70   index: 778
TimeSpanDataQueue.js:71   dt:    0.012
TimeSpanDataQueue.js:72   value: 0
TimeSpanDataQueue.js:69 -------
TimeSpanDataQueue.js:70   index: 777
TimeSpanDataQueue.js:71   dt:    0.012
TimeSpanDataQueue.js:72   value: 0
TimeSpanDataQueue.js:69 -------
TimeSpanDataQueue.js:70   index: 776
TimeSpanDataQueue.js:71   dt:    0.016
TimeSpanDataQueue.js:72   value: 0
TimeSpanDataQueue.js:69 -------
</details>

**Comment by jbphet** [comment] 2021-05-21 23:27
> Almost guaranteed! ?profiler has me running at 300 fps, which is expected on my device.

@phet-steele - Color me skeptical on the 300 FPS bit.  That's 5x the nominal rate of 60 FPS, and the data you collected does not seem to indicate that rate.  The profiler may be running into the same problem that the sim is, which is that it was assuming a nominal frame rate of 60 FPS, and if it gets something different, things go south.

The data collected by @phet-steele in the previous comment seems to indicate that his system is running at a frame rate of around 75 FPS.  @phet-steele - Can you check the refresh rate of your display and see if that is the value and report back with whatever you find?

That's part 1.  Part 2 is to test with the current version of master and see if the problem has gone away.  If it has, please also test that the behavior of the pressure gauge is the same or similar enough to the published version (you may have to test the previous version on a different machine if this problem prevents it from running it).  And finally, check that the performance hasn't degraded significantly with this change.  You'll have to use a built version to make an apples-to-apples comparison to the published sim.

Feel free to contact me on Slack if you have any questions on this.  I'll write up an explanation of the problem and solution once we verify that this works (or come up with something else if it doesn't).

**Comment by jonathanolson** [comment] 2021-05-24 15:56
Can you keep me informed of whether a patch for this will go into the maintenance releases?

**Comment by jbphet** [comment] 2021-05-24 16:51
@jonathanolson - It is very likely that a patch will go in for states-of-matter and states-of-matter-basics, but it dependent upon what we hear back from @phet-steele and when.  If there is something specific that you'd like me to do differently versus the usual process for this, please let me know.

**Comment by jonathanolson** [comment] 2021-05-24 16:59
> If there is something specific that you'd like me to do differently versus the usual process for this, please let me know.

Release branches are still locked down to due the maintenance process, so let me know when it's ready to move to the branch.

**Comment by phet-steele** [comment] 2021-05-24 19:03
> Can you check the refresh rate of your display and see if that is the value and report back with whatever you find?

My refresh rate is 300 hz and this site also says I am getting 300 fps 😁 https://www.testufo.com/refreshrate

> Part 2 is to test with the current version of master and see if the problem has gone away.

Sure seems like the problem has gone away, and I don't see performance issues on the mac and win 10 I have either.

**Comment by jbphet** [comment] 2021-05-25 16:03
> My refresh rate is 300 hz and this site also says I am getting 300 fps

Okay.  I'd just never heard of a refresh rate that high, but looking around online I _do_ see monitors that spec that rate, so I stand corrected.  We're not see animation frame requests that fast, so I'm curious about how high refresh rates and the standard browsers `window.requestAnimationFrame` method works, but that's a question for another time.

> Sure seems like the problem has gone away, and I don't see performance issues on the mac and win 10 I have either.

Cool, good to hear.  I'll move forward with a maintenance release to fix the issue.

In summary, the problem was that the class that I had created to track and average the pressure data over time used pre-allocated memory to try to maximize its performance.  This pre-allocation step assumed a standard rate for `window.requestAnimationFrame` of 60 FPS.  Faster frame rates caused the buffer to overflow.  In the non-built version, this hits an assertion.  In the built version, it just stops putting pressure information into the buffer, so the pressure gets stuck.  I've modified the code to pre-allocate much of the needed memory, and then to expand the allocation if necessary.  I tested this by intentionally under-allocating the memory.

**Comment by jbphet** [comment] 2021-05-25 16:04
@jonathanolson - I'm ready to do a maintenance release for this issue.  How should we proceed?

**Comment by jbphet** [comment] 2021-06-01 19:29
For the record, @kathy-phet told me that she and @KatieWoe discussed whether or not to add a step to the QA process to test faster frame rates and decided against doing so.  @kathy-phet recommended that, for now, we add an item to the code review checklist to look for any code that assumes a certain frame rate.  I added such an item in https://github.com/phetsims/phet-info/commit/1f1c0af69e3209a84b231f880ccc7125f73c095b#diff-f89f7f6ce4981e08a13b7a7a07456365dc54b1d206f3ae36af5b82a4a5f72bb3.

**Comment by phet-steele** [comment] 2021-06-02 22:17
> @kathy-phet recommended that, for now, we add an item to the code review checklist to look for any code that assumes a certain frame rate.

My guess is phetsims/molecule-shapes/issues/180 another one of this class of issue.

**Comment by jbphet** [comment] 2021-06-11 17:58
@jonathanolson - This is ready to go into an RC on the current release branch.  I think it would be best if I did it myself, since I can verify it more easily and know what to look for.  Is it okay for me to pull this onto the current release branch for states-of-matter and states-of-matter-basics?  Also, should I do the RC, or is there an upcoming one that you would make this a part of?

**Comment by jbphet** [comment] 2021-06-14 19:59
This is being tested by QA at the moment in an RC, see https://github.com/phetsims/QA/issues/656.  If QA testing passes, we can close it.  I'll unassign @jonathanolson, since it's pretty much up to me to follow up.

**Comment by jbphet** [comment] 2021-06-15 14:59
Assigning @KatieWoe as an assignee so that she or another member of the QA team can update based on the testing of the current RC.

**Comment by KatieWoe** [comment] 2021-06-15 15:15
@phet-steele said in https://github.com/phetsims/QA/issues/656#issuecomment-860981271
>I checked all the links in #656 (comment) for phetsims/states-of-matter/issues/354, and they all correctly calculated pressure. I tried both Win 10 Chrome and FF.

**Comment by jbphet** [comment] 2021-06-15 15:44
Excellent.  Closing.

**Closed by jbphet** 2021-06-15 15:44 UTC
Labels: type:bug
