### ISSUE TITLE
moleculeDataSet.moleculeRotationAngles should not have NaN values set to it

### ISSUE THREAD

**Issue by zepumph** [phetsims/states-of-matter#365] opened 2023-12-07 23:15 UTC
While improving our testing over in https://github.com/phetsims/phet-io-wrappers/issues/542, we seemed to have exposed a weird bug where the moleculeDataSet has `null` values in a Float64Array. I can't track it down just yet, but it is failing on CT. I'll keep looking.  I'm really confused because I thought there was validation in Float64ArrayIO, but it doesn't seem to be complete or working right.

**Comment by zepumph** [comment] 2023-12-07 23:15
<details>

```
Subject: [PATCH] combine tests that reload Client,  https://github.com/phetsims/phet-io-wrappers/issues/542
---
Index: tandem/js/types/StateSchema.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/tandem/js/types/StateSchema.ts b/tandem/js/types/StateSchema.ts
--- a/tandem/js/types/StateSchema.ts	(revision b11ebcba0ab00ce01161e6aed52d0ccdcd369dde)
+++ b/tandem/js/types/StateSchema.ts	(date 1701988615807)
@@ -231,6 +231,7 @@
           else {
             if ( !schema[ key ].isStateObjectValid( compositeStateObject[ key ], false ) ) {
               assert && toAssert && assert( false, `stateObject is not valid for ${key}. stateObject=`, compositeStateObject[ key ], 'schema=', schema[ key ] );
+              debugger;
               valid = false;
             }
           }
@@ -252,7 +253,11 @@
         assert( validationError === null, 'valueStateObject failed validation', valueStateObject, validationError );
       }
 
-      return Validation.isValueValid( valueStateObject, this.validator! );
+      const isValieTemp = Validation.isValueValid( valueStateObject, this.validator! );
+      if ( !isValieTemp ) {
+        debugger;
+      }
+      return isValieTemp;
     }
   }
 
Index: tandem/js/types/Float64ArrayIO.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/tandem/js/types/Float64ArrayIO.ts b/tandem/js/types/Float64ArrayIO.ts
--- a/tandem/js/types/Float64ArrayIO.ts	(revision b11ebcba0ab00ce01161e6aed52d0ccdcd369dde)
+++ b/tandem/js/types/Float64ArrayIO.ts	(date 1701990659187)
@@ -15,12 +15,16 @@
   valueType: Float64Array,
   toStateObject: array => {
     const result: number[] = [];
-    array.forEach( float => result.push( float ) );
+    array.forEach( float => {
+      assert && assert( typeof float === 'number' ); // eslint-disable-line no-simple-type-checking-assertions
+      return result.push( float );
+    } );
     return result;
   },
   fromStateObject: stateObject => new Float64Array( stateObject ),
   stateSchema: StateSchema.asValue<Float64Array, number[]>( 'Float64Array', {
-    isValidValue: ( value: number[] ) => Array.isArray( value ) && value.find( v => typeof v !== 'number' ) === undefined
+    // TODO: Float64Array should not support null
+    isValidValue: ( value: number[] ) => Array.isArray( value ) && value.find( v => typeof v !== 'number' && typeof v !== null ) === undefined
   } ),
 
   // Float64ArrayIO is a data type, and uses the toStateObject/fromStateObject exclusively for data type serialization.
Index: tandem/js/types/IOType.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/tandem/js/types/IOType.ts b/tandem/js/types/IOType.ts
--- a/tandem/js/types/IOType.ts	(revision b11ebcba0ab00ce01161e6aed52d0ccdcd369dde)
+++ b/tandem/js/types/IOType.ts	(date 1701988495591)
@@ -431,6 +431,9 @@
     if ( this.stateSchema ) {
       const validSoFar = this.stateSchema.checkStateObjectValid( stateObject as SelfStateType, toAssert, schemaKeysPresentInStateObject );
 
+      if ( validSoFar === false ) {
+        debugger;
+      }
       // null as a marker to keep checking up the hierarchy, otherwise we reached our based case because the stateSchema was a value, not a composite
       if ( validSoFar !== null ) {
         return validSoFar;
@@ -448,6 +451,7 @@
       Object.keys( stateObject ).forEach( key => {
         const keyValid = schemaKeysPresentInStateObject.includes( key );
         if ( !keyValid ) {
+          debugger;
           valid = false;
         }
         assert && toAssert && assert( keyValid, `stateObject provided a key that is not in the schema: ${key}` );
Index: states-of-matter/js/common/model/MoleculeForceAndMotionDataSet.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/states-of-matter/js/common/model/MoleculeForceAndMotionDataSet.js b/states-of-matter/js/common/model/MoleculeForceAndMotionDataSet.js
--- a/states-of-matter/js/common/model/MoleculeForceAndMotionDataSet.js	(revision 352b4c5f639c9c0dd2cf3c427ed84b76661d44ee)
+++ b/states-of-matter/js/common/model/MoleculeForceAndMotionDataSet.js	(date 1701990827097)
@@ -261,6 +261,7 @@
    * @public
    */
   setMoleculeRotationAngles( rotationAngles ) {
+    assert && assert( _.every( rotationAngles, x => typeof x === 'number' ), 'no nulls' )
     this.moleculeRotationAngles = rotationAngles;
   }
 
@@ -374,6 +375,8 @@
    * @public - for phet-io support only
    */
   toStateObject() {
+    const moleculeRotationAngles = Float64ArrayIO.toStateObject( this.moleculeRotationAngles );
+    assert && assert( _.every( moleculeRotationAngles, x => typeof x === 'number' ) );
     return {
       atomsPerMolecule: this.atomsPerMolecule,
       numberOfAtoms: this.numberOfAtoms,
@@ -388,7 +391,7 @@
       moleculeForces: ArrayIONullableIOVector2IO.toStateObject( this.moleculeForces ),
       nextMoleculeForces: ArrayIONullableIOVector2IO.toStateObject( this.nextMoleculeForces ),
       insideContainer: ArrayIOBooleanIO.toStateObject( this.insideContainer ),
-      moleculeRotationAngles: Float64ArrayIO.toStateObject( this.moleculeRotationAngles ),
+      moleculeRotationAngles: moleculeRotationAngles,
       moleculeRotationRates: Float64ArrayIO.toStateObject( this.moleculeRotationRates ),
       moleculeTorques: Float64ArrayIO.toStateObject( this.moleculeTorques ),
       nextMoleculeTorques: Float64ArrayIO.toStateObject( this.nextMoleculeTorques )
@@ -424,6 +427,7 @@
     const moleculeRotationAngles = Float64ArrayIO.fromStateObject( stateObject.moleculeRotationAngles );
     const moleculeRotationRates = Float64ArrayIO.fromStateObject( stateObject.moleculeRotationRates );
     const moleculeTorques = Float64ArrayIO.fromStateObject( stateObject.moleculeTorques );
+    const nextMoleculeTorques = Float64ArrayIO.fromStateObject( stateObject.nextMoleculeTorques );
     const insideContainer = ArrayIOBooleanIO.fromStateObject( stateObject.insideContainer );
     for ( let i = 0; i < this.numberOfMolecules; i++ ) {
       this.moleculeCenterOfMassPositions[ i ] = moleculeCenterOfMassPositions[ i ];
@@ -433,6 +437,7 @@
       this.moleculeRotationAngles[ i ] = moleculeRotationAngles[ i ];
       this.moleculeRotationRates[ i ] = moleculeRotationRates[ i ];
       this.moleculeTorques[ i ] = moleculeTorques[ i ];
+      this.nextMoleculeTorques[ i ] = nextMoleculeTorques[ i ];
       this.insideContainer[ i ] = insideContainer[ i ];
     }
   }

**Comment by zepumph** [comment] 2023-12-08 18:58
Ahh. I finally cracked it. The initialization isn't correct, and some initial values are a`NaN`, which get coerced into `null` later on by PhET-iO.

**Comment by zepumph** [comment] 2023-12-08 19:16
Ok. I found the spot where SOM was setting NaN to the rotation angles and added an assertion. Over to @jbphet to fix the sim-specific assertion. I'm happy to help if desired.

**Comment by zepumph** [comment] 2023-12-11 19:16
I really don't know of a good default or temp fix to silence this assertion right now. So I'm just leaving it failing every test on CT. `inertiaInverse` has a divide by 0, but I don't know what a good inertia should be otherwise.

**Comment by jbphet** [comment] 2023-12-12 19:31
The previous code (which I had written) was using a value of 0 for the rotational inertia of single atoms.  The code that calculates the rotation angle was taking the inverse of this value as an optimization, which was leading to an infinite value, which then led to NaN values in the rotations.  Since rotation of single atoms isn't shown at all in the sim, it doesn't really matter what value is used here, so I've changed it to 1.  I've done a bit of regression testing (though not much), and this seems to work fine.

I'll leave this open for a bit and will watch CT.  If the issue clears up, I'll close.

**Comment by jbphet** [comment] 2023-12-12 20:54
CT has cleared up.  Closing.

**Closed by jbphet** 2023-12-12 20:54 UTC
Labels: type:automated-testing
