### ISSUE TITLE
Adjustable Attraction bursts lid earlier than other gases

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/states-of-matter#124] opened 2016-06-03 21:05 UTC
For phetsims/tasks#609
Test device: Bates, Lave
Operating System: Win 7, iOS 8.4.1
Browser: Chrome, Safari

Problem description: When using the Adjustable Attraction atoms, the lid will burst at about 130 atm instead of going all the way up to OVERLOAD at 200 atm like all the other gases do. Seen on both Windows and iPad 2.

Screenshots: 
Paused and stepping frame by frame:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/11947677/15792767/9476cdb0-299c-11e6-96b4-c2885136f4d6.gif)

Troubleshooting information (do not edit):
Name: ‪States of Matter‬
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.6/states-of-matter_en.html?
Version: 1.0.0-dev.6 2016-06-02 15:57:50 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36
Language: en-US
Window: 1366x667
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 253
Texture: size: 8192 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"1f807347","branch":"master"},"babel":{"sha":"b90d3542","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"chipper":{"sha":"a01a8e0f","branch":"master"},"dot":{"sha":"04efe0bc","branch":"master"},"joist":{"sha":"76d9aa21","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"nitroglycerin":{"sha":"ad3cb990","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"4fb54ac9","branch":"master"},"scenery-phet":{"sha":"1bd4aed0","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"states-of-matter":{"sha":"83399aac","branch":"master"},"sun":{"sha":"b708d54f","branch":"master"},"tandem":{"sha":"0e40c775","branch":"master"}}

**Comment by aadish** [comment] 2016-06-07 22:01
this behavior is consistent with java version of the simulation and currently have no idea how to deal with it

in discussion with @jbphet it seems it is not a bug but will take a look later

**Comment by arouinfar** [comment] 2016-06-07 22:28
It's not just Adjustable Attraction that blows the lid too early -- argon and oxygen blow before the pressure reaches overload.

@phet-steele mentioned this problem could be related to the interaction strength. What's puzzling is that neon and water are both capable of reaching pressure overload, despite having VERY different intermolecular forces. Neon would experience very weak London dispersion forces, while water experiences hydrogen bonding -- these are at opposite ends of the spectrum.

**Comment by jbphet** [comment] 2016-07-26 16:56
The root of this problem is that the code has (or had) a mapping algorithm for internal model pressure to pressure in atmosphere that was different depending on the atom/molecule selection.  This was done in order to have more realistic values of pressure.  However, since the internal pressure value is the determining factor in what causes the container to explode, different pressure mappings cause the container to explode at what appears to the user as different pressure values.

I went ahead and modified the code that converts from internal model pressure to pressure in atmospheres to use the same conversion algorithm for all atom/molecule selections.  This works great in the sense that the pressure gauge now always shows "OVERLOAD" as the container explodes.  It's my opinion that the fact that these readings are somewhat less realistic isn't going to bother any of our users, but I'd like to know if @arouinfar and/or @ariel-phet concur.  Assigning to them for their input.

**Comment by arouinfar** [comment] 2016-07-26 17:40
@jbphet that sounds reasonable to me and @amyh-phet.

**Comment by ariel-phet** [comment] 2016-07-26 22:41
I agree, sounds reasonable to me

**Comment by jbphet** [comment] 2016-07-28 15:12
Great.  This should now be addressed, assigning to @phet-steele to verify on master and close if the problem appears to be corrected.

**Comment by phet-steele** [comment] 2016-08-03 19:43
👍

**Closed by phet-steele** 2016-08-03 19:43 UTC
Labels: type:bug
