### ISSUE TITLE
Why did the HearterCoolerNode get smaller?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#224] opened 2018-09-12 20:18 UTC
@jbphet @arouinfar I can't find a documented decision on why this is, but the `HeaterCoolerNode` in 1.1.0-rc.1 is smaller than the published sim (1.0.5). Por que?

NEW:
![image](https://user-images.githubusercontent.com/5863899/45450721-4859e280-b696-11e8-9550-4dd078df56f9.png)

OLD:
![image](https://user-images.githubusercontent.com/5863899/45450745-5b6cb280-b696-11e8-9cc1-6abb60178e7b.png)

Seen on Win 10 Chrome. For phetsims/QA/issues/185.

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-rc.1/phet/states-of-matter_en_phet.html
Version: 1.1.0-rc.1 2018-09-12 18:56:30 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Language: en-US
Window: 1920x943
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"d7ba44e2","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"bbbb514a","branch":"HEAD"},"dot":{"sha":"820111c8","branch":"HEAD"},"joist":{"sha":"fb860843","branch":"HEAD"},"kite":{"sha":"59755f7e","branch":"HEAD"},"nitroglycerin":{"sha":"ccaab9cd","branch":"HEAD"},"phet-core":{"sha":"68a89cc4","branch":"HEAD"},"phet-io":{"sha":"364077cf","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"abc4ae3e","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"429886e7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ef0b0b0c","branch":"HEAD"},"phet-io-wrappers":{"sha":"7ec1a04a","branch":"HEAD"},"phetcommon":{"sha":"22b158d0","branch":"HEAD"},"query-string-machine":{"sha":"c2e502fb","branch":"HEAD"},"scenery":{"sha":"415371c3","branch":"HEAD"},"scenery-phet":{"sha":"94b92879","branch":"HEAD"},"sherpa":{"sha":"a9fd066b","branch":"HEAD"},"states-of-matter":{"sha":"de26f688","branch":"HEAD"},"sun":{"sha":"3086e97a","branch":"HEAD"},"tambo":{"sha":"0e5b9133","branch":"HEAD"},"tandem":{"sha":"a2348c0c","branch":"HEAD"}}
</details>

**Comment by jbphet** [comment] 2018-10-03 23:48
I tried to do some forensics on why this ended up a different size, but it was taking a lot of time, so I bailed and just adjusted the size to more closely match the previous release.  The answer wasn't as simple as "somebody said it should be smaller so I changed it".  I think it was actually caused by some mods to common code.  At any rate, it's now much closer to the original.

**Comment by jbphet** [comment] 2018-10-05 20:02
Note to testers: The heater cooler node size is now much closer to the currently published version, but it's not *exactly* the same.  It just worked out a little better in the code to have this size versus and exact match.  Unless you feel that there is a problem with this slight adjustment, this small change shouldn't be considered a problem.

**Comment by KatieWoe** [comment] 2018-10-16 17:18
Confirm 1.1.0-rc.2

**Comment by jbphet** [comment] 2018-10-29 23:11
Deployed in v1.1.0, closing.

**Closed by jbphet** 2018-10-29 23:11 UTC
Labels: status:fixed-awaiting-deploy, type:question
