### ISSUE TITLE
Factor out/minimize overrides files.

### ISSUE THREAD

**Issue by samreid** [phetsims/states-of-matter#303] opened 2020-06-29 20:32 UTC
Discovered during https://github.com/phetsims/states-of-matter/issues/299.  The overrides files must be maintained along with the simulation, and things will be simpler if we can minimize them as much as possible.

This can be done safely by comparing `grunt generate-phet-io-api` before and after a change.  I'll take a look.

**Comment by samreid** [comment] 2020-06-29 21:16
I've committed several changes factoring out overrides from several places into the point of origination, I was able to do around one per minute (I focused on the ones that did not require simulation-specific knowledge), and it seemed a good use of time.  For instance, atomic interactions is down from 27 to 19 overrides.  I recommend taking a bit more time to look through and see if anything else is easy to factor out.

**Comment by jbphet** [comment] 2020-06-30 19:49
@samreid - I have a few questions, and a comment, on this:

+ It looks like you moved some overrides and not others.  In your comment you said, "I recommend taking a bit more time to look through and see if anything else is easy to factor out."  Is the goal to move them all?  If so, what is the purpose of the overrides file?  If not, what are the guiding principles for what should be in the overrides file and what should be in the code?
+ I ran `grunt generate-phet-io-api` as you suggested about, and it generated a file that includes a number of differences that look like they come from common code.  Also, the format of the file name seems different from what's in the directory now, and the file seems to include a date a time in the name (`2020-4-30_11.20.41.json` versus `6-30-2020_1.39.04_PM.json`).  Am I supposed to check these in on changes, or is the idea just to compare them and look for the changes that I intended to make (and to ignore things from common code)?
+ Finally, just a heads up: The changes for this caused CT errors in atomic-interactions and states-of-matter-basics, so if you do anything else on this, please make sure to check those sims as well.  See https://github.com/phetsims/atomic-interactions/issues/87 and https://github.com/phetsims/states-of-matter-basics/issues/28.

**Comment by samreid** [comment] 2020-06-30 21:50
> Is the goal to move them all? If so, what is the purpose of the overrides file? If not, what are the guiding principles for what should be in the overrides file and what should be in the code?

Let's consider `temperatureInKelvinProperty`.  Before the commits above we had:

// states-of-matter-overrides.js
```js
  "statesOfMatter.phaseChangesScreen.model.temperatureInKelvinProperty": {
    "phetioFeatured": true
  },
...
  "statesOfMatter.statesScreen.model.temperatureInKelvinProperty": {
    "phetioFeatured": true
  },
```

// states-of-matter-basics-overrides.js
```js
  "statesOfMatterBasics.phaseChangesScreen.model.temperatureInKelvinProperty": {
    "phetioFeatured": true
  },
// ...
  "statesOfMatterBasics.statesScreen.model.temperatureInKelvinProperty": {
    "phetioFeatured": true
  },
```

The commits removed those 12 lines of code and added one line of code in the declaration for `temperatureInKelvinProperty`:

```js
phetioFeatured: true,
```

The goal is not to move everything out of the overrides file, but for it to handle exception cases where doing it in the code would be more burdensome.  In this example, `temperatureInKelvinProperty` is always supposed to be featured, so it makes sense to centralize that in a single point.

Hypothetically, if there was another property `temperatureInCelsiusProperty` which was featured in screen1.scene2, screen2.scene1, screen3.scene2 and screen4.scene1 then it might be simplest to address that in the overrides file rather than try to pass that through correctly to each situation.

> I ran grunt generate-phet-io-api as you suggested about, and it generated a file that includes a number of differences that look like they come from common code

Are you comparing to the checked in file, such as states-of-matter/build-phet-io-api/2020-4-30_11.20.41.json?  If so, you are seeing the culmination of all the changes since the end of April which includes common code changes.  I used `grunt generate-phet-io-api` before starting the changes in this issue, then again after each change to make sure nothing was disrupted.

> Am I supposed to check these in on changes, or is the idea just to compare them and look for the changes that I intended to make (and to ignore things from common code)?

Those files do not need to be committed.  In https://github.com/phetsims/phet-io/issues/1648#issuecomment-614848624 we determined that the API files would not normally need to be checked in.  In https://github.com/phetsims/phet-io/issues/1672 we are how and where to check them in if they need to be checked in.

> Finally, just a heads up: The changes for this caused CT errors in atomic-interactions and states-of-matter-basics

Thanks for the heads up, I'll be more careful.  For my records, the reason I failed to detect these errors is that I was only using `grunt generate-phet-io-api` in those repos and that doesn't run with assertions.

**Comment by kathy-phet** [comment] 2020-07-02 14:16
Let's discuss this at PhET-iO meeting. 

For several reasons, I am not very keen on adding this step to the development process and prefer the approach we have been using: 
1) I favor keeping all of the sim-specific featured elements within the overrides file, and just having the common code featured elements in the code. This helps me as an instructional designer conceptualize where things live in terms of setting something as featured and creates an approach that can be very consistent sim to sim.
2) It does add time and steps to the process, basically duplicating the work the designer has already completed, and I do not think it is a good use of developer time should be responsible for combing through the overrides and deciding what is and is not common across the list. 
3) While it does save lines, it seems like this is a minimal save since all of those lines were in the overrides file. And it instead adds lines and complication to the main sim code which is where the maintenance has to be. Of course, I'm not a developer so that is a outside perspective on that point. 
4) It adds another step to an already pretty complicated process. I prefer to be done with the featured aspect after the instructional designer has committed the file. As above, the changes have the potential of creating issues that take additional time. 

So let's discuss today.

**Comment by samreid** [comment] 2020-07-02 16:30
My understanding from the process @pixelzoom described for Natural Selection is that the design team indicated generally and broadly what should be featured so that @pixelzoom could determine which were appropriate to specify in the code, then the designers applied the overrides to the rest.

Looking forward to discussing further.

**Comment by pixelzoom** [comment] 2020-07-02 16:34
That's not the case with Natural Selection.  There has been no "featured" discussion, and there are no plans to put `phetioFeatured: true` in any sim-specific code - it will be specified by designers using Studio, and will therefore be in the overrides.js file.

**Comment by samreid** [comment] 2020-07-02 16:36
Thanks for correcting me--I had some recollection about @pixelzoom reporting cases where he determined when to put metadata in the code vs in the override file.  Am I misremembering that?

**Comment by pixelzoom** [comment] 2020-07-02 16:44
Studio (with `?admin`) lets you specify `phetioDocumentation`, `phetioFeatured`, `phetioReadOnly`, and `phetioHighFrequency`.    My recollection of our decision about these metadata is:

* `phetioFeatured` should be specified exclusively through Studio

* The other metadata can be specified in the code or through Studio, but not both.  If it's specified in the code and modified in Studio, then the developer should move the specification from overrides.js to code.

**Comment by samreid** [comment] 2020-07-02 16:55
I also noticed this comment: https://github.com/phetsims/studio/issues/25#issuecomment-598316108 from March 12:

> At today's phet-io meeting, we determined that designers will often use "Featured" overrides, but often communicate to developers if other overrides are needed, so those can be applied in the code.

**Comment by kathy-phet** [comment] 2020-07-02 17:00
Chris and other developers have been putting phetioReadOnly in the code in places where providing customization access in Studio would break the sim. This is the one place where the metadata has been going in the code, and I agree that this belongs in the code itself. The designers typically communicate this to the developers when we notice that something will break the sim if used incorrectly.

**Comment by samreid** [comment] 2020-07-02 17:04
How far would we want to go in this direction?  I noticed `phetioFeatured: true` in Beer's Law Lab code.  Should that be moved to an overrides file?  Should developers be forbidden from factoring something out of this file, even if it only takes 2 minutes?  The overrides file needs maintenance like any file and in one case caused a problem where a developer updated the code but neglected to update the overrides file.

**Comment by pixelzoom** [comment] 2020-07-02 17:08
Beer's Law Lab has many problems, doesn't use current patterns, and is overdue for a major overhaul - see https://github.com/phetsims/beers-law-lab/issues/230.  I would anticipate that `phetioFeatured: true` will be removed.

**Comment by samreid** [comment] 2020-07-02 17:42
From our discussion today, we agreed that even if a family of Properties in a simulation is to be featured, they should still be independently toggled with studio ?admin mode.  All other metadata will be specified in code.  We will leave `phetioDocumentation` editable in studio, but we expect it to be used rarely.

**Comment by samreid** [comment] 2020-07-02 17:45
I'll move things back to the overrides files for this simulation.  @kathy-phet said for other simulations that specify `phetioFeatured` in the sim code, those can be addressed when we revisit those simulations.

**Comment by samreid** [comment] 2020-07-03 17:07
I reverted the changes and used `grunt generate-phet-io-api` to confirm that the overall API was not disturbed.  @jbphet can you please review?

**Comment by jbphet** [comment] 2020-07-08 22:20
I reviewed this by skimming through the overrides file history for SOM, SOMB, and AI, and they look pretty reasonable to me.  The only thing in them is the `phetioFeatured` settings and they look pretty close to what I remember.  The featured items will likely get reviewed before final publication too, so I think this is safe to close.

**Closed by jbphet** 2020-07-08 22:20 UTC
Labels: dev:code-review, status:ready-for-review
