### ISSUE TITLE
iPad2 - Phase changes screen - Container lid movement is very slow

### ISSUE THREAD

**Issue by kmsravindra** [phetsims/states-of-matter#17] opened 2015-01-20 11:05 UTC
When Container lid is touched and moved, it moves very slowly on iPad2.

**Comment by jbphet** [comment] 2015-05-19 21:15
This is still an issue in v1.0.0-dev.5 (http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.5/states-of-matter_en.html).

**Comment by notsiddhartha** [comment] 2015-05-20 14:40
The cause for this seems to be allocations and the general sim performance on iPad2. 
While pushing the lid, I have observed ~160 Vector2 allocations per frame (from Path.setShape while updating the DialGuageNode connector) and the performance drops to ~10 fps from ~20 fps.

This issue looks similar to https://github.com/phetsims/fluid-pressure-and-flow/issues/245

**Comment by kmsravindra** [comment] 2015-05-20 17:49
@ariel-phet, @jbphet  Request your  direction on this issue wrt to the above comment.

**Comment by jbphet** [comment] 2015-05-20 21:09
Assigning to @jonathanolson to have a look and potentially recommend a more efficient way to update the shape of the shape that connects the gauge to the container.

@kmsravindra - PhET will take it from here.

**Comment by jonathanolson** [comment] 2016-03-10 17:29
Checked briefly into DialGaugeNode.

Many shapes could be cached and not re-created every time. If it's the elbowHeight changing every frame, it would be helpful for me to collaborate with the developer for the sim (maybe we can have part of the shape remain the same, or use transforms)?

@jbphet, let me know if you'd be the person to talk to?

**Comment by jbphet** [comment] 2016-03-10 19:15
This sim is on hold for now.  @jonathanolson - I or whoever is ultimately tasked with working on this will talk with you when this sim is back on the short list.

**Comment by phet-steele** [comment] 2016-06-07 17:41
@arouinfar states that performance while dragging the container lid is acceptable.

**Closed by phet-steele** 2016-06-07 17:41 UTC
Labels: status:fixed-pending-testing
