### ISSUE TITLE
PhET-iO code review

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#299] opened 2020-06-23 17:17 UTC
PhET-iO instrumentation has been added to this sim for https://github.com/phetsims/states-of-matter/issues/245, and part of the process is to have a code review.  However, there is an impending dev release to the client (see https://github.com/phetsims/states-of-matter/issues/296), and in a Slack conversation @kathy-phet said she did not want to delay the client release in order to complete the code review.

@samreid - I thought I'd start by assigning this to you, you can re-assign as you and the phet-io team see fit.  It all likelihood this will go on in parallel with the client's evaluation of the dev version.

**Comment by samreid** [comment] 2020-06-23 18:09
Thanks, I labeled it for PhET-iO Wednesday meeting for discussion.

**Comment by zepumph** [comment] 2020-06-25 17:59
@samreid volunteered. Thanks! This doesn't blockdev, and so should be done at a medium to medium/high priority as it will block RC publication.

**Comment by samreid** [comment] 2020-06-26 00:00
I labeled it high to put it on my radar, but likely I shouldn't make any commits until there is a dev version.

**Comment by zepumph** [comment] 2020-06-26 00:18
A dev version has been made for SOM! See #296.

**Comment by samreid** [comment] 2020-06-29 19:41
@jbphet can you please identify the scope for this review?  Is all of the code under states-of-matter/js and states-of-matter-basics/js?  Since this has passed design team and dev testing, will I need to review any runtime parts, or is this all about implementation?

**Comment by jbphet** [comment] 2020-06-30 16:51
@samreid asked:

> [C]an you please identify the scope for this review? Is all of the code under states-of-matter/js and states-of-matter-basics/js and atomic-interactions/js? Since this has passed design team and dev testing, will I need to review any runtime parts, or is this all about implementation?

There isn't much code in states-of-matter-basics and atomic-interactions, since they both derive entirely from states-of-matter, so I'd like to request that yes, you code review those as well, but I don't think that there will be much to it.  Let me know if you'd like separate issues for this, but it seems unnecessary to me.

I'm not entirely sure what you mean by "[W]ill I need to review any runtime parts, or is this all about implementation?"  I'm thinking that you're looking through the code that was added to support phet-io and making sure that I've followed the latest procedures and recommendations for how this is done, and also checking that I haven't done anything that will cause problematic behavior or make maintenance more difficult than it has to be.  I don't think you need to do any testing of the sim.  If that doesn't answer your question, let's set up a Zoom call to clarify.

**Comment by samreid** [comment] 2020-07-01 01:57
From the code review document:

> At the very least, be sure to know what amount of instrumentation this sim supports. Describing this further goes beyond the scope of this document.

Is the simulation feature-complete for PhET-iO?  After this dev version could we move forward to RC, or is there other work that would be required first?

**Comment by jbphet** [comment] 2020-07-30 23:11
The REVIEW comments have all been addressed, as have the issues that resulted from the review.  Some of those issues were closed and some were left open to make sure that they were tested during the RC process.  @samreid - back to you to review the commits and issue responses and either close or send back to me if you feel that there is more to be done on this.

**Comment by samreid** [comment] 2020-08-04 22:27
I confirmed the REVIEW comments have been addressed nicely, thanks!  I think the last issue is https://github.com/phetsims/states-of-matter/issues/307, we will finish there.  Nice work @jbphet, closing.

**Closed by samreid** 2020-08-04 22:27 UTC
Labels: priority:2-high, status:ready-for-review
