### ISSUE TITLE
Changing the Atoms and Molecules panel title to a long string causes an unexpected space when launched

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#328] opened 2020-08-12 18:48 UTC
For https://github.com/phetsims/QA/issues/525. This seems to happen when launching from studio, and not when using `stringTest=long`. This relates to the client request:
>Edit the Atoms and Molecules panel title

To reproduce:
1. Use `statesOfMatter.interactionScreen.view.atomsControlPanel.title.textProperty`
2. Type a string long enough for the letters displayed in the sim to shrink a size
3. Observe any space in the sim preview
4. Press backspace to seemingly remove it (make sure string is still long enough to have shrunk)
5. Launch sim

![largespace](https://user-images.githubusercontent.com/41024075/90055083-0aa6cf80-dc9a-11ea-9eed-916748a7ca44.gif)

**Comment by KatieWoe** [comment] 2020-08-12 19:35
Seems to cause issues with other text as well, such as the molecules selection box.

**Comment by jbphet** [comment] 2020-08-14 16:46
@arouinfar, @kathy-phet, and I reviewed this issue yesterday in order to decide if it was blocking for the 1.2 release and we concluded that it was.  However, I think we were misled by the nature of the video recording.  The recording makes it look like the screen layout is quite messed up on the launch, but when I started reading the description more carefully and trying to duplicate the problem, I began to suspect that it is just the spacing of the title that is being described.  I checked in with @KatieWoe and she confirmed this, and said that the recording was just an artifact of how she had recorded the launched sim.

With this in mind, I no longer feel that this is blocking for the RC.  I'll spend a few more minutes on it to see if it's a quick and easy fix but, if it isn't, I'll update and move on to other things.

**Comment by jbphet** [comment] 2020-08-14 17:00
I did a bit more investigation and didn't find a quick and obvious fix.  This seems like it has something to do with the interplay between max width, changes to a node's local bounds, and dynamic updates of text values.  In this particular case, the string is in a `BackgroundNode`, and it seems that the size and positioning of the background node isn't getting updated quite as one would expect, even though it is listening to the local bounds of the content node.

For the record, I tested with `stringTest=long`, and the layout was fine.

I'm going to assign this to @zepumph, since he was involved in the creation of `BackgroundNode` and is one of the primary phet-io developers.  The idea of setting strings to very long values using phet-io seems to me to be a rare case, so I'll leave it up to him to decide whether this is worthy of any further investment of time.

**Comment by arouinfar** [comment] 2020-08-14 21:39
That all sounds reasonable to me @jbphet.

**Comment by KatieWoe** [comment] 2020-08-17 23:17
This seems worse in https://github.com/phetsims/QA/issues/531
![worse](https://user-images.githubusercontent.com/41024075/90453326-8dba9200-e0ad-11ea-9a51-71ab771ffa63.png)

**Comment by jbphet** [comment] 2020-08-18 16:16
I've removed the "blocks-sim-publication" label because I feel that this is a rare use case with fairly minor consequences.  @arouinfar - please chime in on this.

**Comment by arouinfar** [comment] 2020-08-19 18:06
@jbphet agreed that this isn't blocking.

It looks like the problem occurs if the custom string is longer than the `maxWidth`.  I don't anticipate this being a common use case, and I am pretty sure the client just wants to delete the string (based on conversations with KP).

**Comment by zepumph** [comment] 2020-08-19 20:02
This feels a bit like a specific sub issue to https://github.com/phetsims/phet-io/issues/1551.

**Comment by kathy-phet** [comment] 2020-08-20 22:56
@jbphet @arouinfar @kathy-phet - We reviewed and decided that it's not important if this bug gets fixed, but if https://github.com/phetsims/phet-io/issues/1551 fixes it, then that's great.

**Closed** 2020-08-20 22:57 UTC
Labels: dev:phet-io, type:bug, type:wontfix
