### ISSUE TITLE
The case of the disappearing dependencies.json

### ISSUE THREAD

**Issue by samreid** [phetsims/states-of-matter#196] opened 2016-12-14 20:02 UTC
As part of https://github.com/phetsims/tasks/issues/753 I was looking into https://github.com/phetsims/joist/issues/389 and noticed there is no dependencies.json here where it should be http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-rc.1/

@jbphet @pixelzoom @jonathanolson any idea what is happening?

**Comment by samreid** [comment] 2016-12-14 20:06
I'm seeing this during a build:

```
~/github/faradays-law$ grunt
Running "eslint:allFiles" (eslint) task

Running "clean" task

Running "requirejs-build" task

Running "after-requirejs-build" task

Done.
~/github/faradays-law$ ls -la build/
total 3328
drwxr-xr-x   5 samreid  staff      170 Dec 14 13:05 .
drwxr-xr-x  17 samreid  staff      578 Dec 14 13:04 ..
-rw-r--r--   1 samreid  staff     1756 Dec 14 13:04 dependencies.json
-rw-r--r--   1 samreid  staff      912 Dec 14 13:05 faradays-law_en-iframe.html
-rw-r--r--   1 samreid  staff  1694379 Dec 14 13:05 faradays-law_en.html
```

**Comment by jbphet** [comment] 2016-12-14 22:04
The dependencies were built correctly by the build server - I checked - but it appears they weren't transferred to the dev server.  I looked into it a bit and ended up logging this issue: https://github.com/phetsims/perennial/issues/29.

**Comment by jbphet** [comment] 2016-12-16 18:44
Unassigning myself, since I'm fairly confident at this point that the issue linked in the comment above is the cause, and doesn't have anything to do with States of Matter specifically.

**Comment by mattpen** [comment] 2017-01-19 05:02
The missing dependencies is definitely related to the bug in phetsims/perennial#29 and will be addressed there.  Closing.

**Closed by mattpen** 2017-01-19 05:02 UTC
