### ISSUE TITLE
support ?shuffleListeners

### ISSUE THREAD

**Issue by zepumph** [phetsims/states-of-matter#294] opened 2020-05-29 01:42 UTC
From phetsims/axon#215, when running with ?shuffleListeners, we get this error: assigning to responsible dev to determine if it is worth fixing:

```
states-of-matter
Uncaught Error: Assertion failed: Setting epsilon is not implemented for this class
Error: Assertion failed: Setting epsilon is not implemented for this class
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at DiatomicVerletAlgorithm.setScaledEpsilon (http://localhost:8080/states-of-matter/js/common/model/engine/AbstractVerletAlgorithm.js:232:15)
    at PhaseChangesModel.setEpsilon (http://localhost:8080/states-of-matter/js/phase-changes/PhaseChangesModel.js:76:45)
    at http://localhost:8080/states-of-matter/js/phase-changes/view/EpsilonControlPotentialGraph.js:161:31
    at listener (http://localhost:8080/axon/js/Multilink.js:38:18)
    at TinyEmitter.emit (http://localhost:8080/axon/js/TinyEmitter.js:69:53)
    at EnumerationProperty._notifyListeners (http://localhost:8080/axon/js/Property.js:273:25)
    at EnumerationProperty.set (http://localhost:8080/axon/js/Property.js:171:14)
    at http://localhost:8080/sun/js/buttons/RadioButtonGroupMember.js:128:14
    at TinyEmitter.emit (http://localhost:8080/axon/js/TinyEmitter.js:69:53)
```

**Comment by jbphet** [comment] 2020-05-29 19:04
Hey @zepumph - can you give me some background on this?  I have a slew of SOM issues that I'm in the process of addressing due to phet-io dev testing and the need to get this to a customer, so when you say, "assigning to responsible dev to determine if it is worth fixing", I feel like I don't have enough information to make that determination.  Did we decide that sims need to pass this test before being publication ready?  Is it necessary for phet-io to work properly?

**Comment by zepumph** [comment] 2020-05-29 22:54
>Did we decide that sims need to pass this test before being publication ready?

Over in https://github.com/phetsims/molarity/issues/189#issuecomment-570388452 and https://github.com/phetsims/molarity/issues/189, The dev team thought that listener order dependencies were enough of a code smell to warrant the following line in the code review checklist 
https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md#build-and-run-checks:

> Does the sim behave correctly when listener order is shuffled? (run with query parameters ea&shuffleListeners and ea&shuffleListeners&fuzz)

I don't think this should be done before phet-io dev test delivery. It feels more like a pre-rc step investigation for maintainability. 

> Is it necessary for phet-io to work properly?

Not that I know of.

**Comment by jbphet** [comment] 2020-06-24 22:28
The order dependency was caused by portions of the simulation reading the MultipleParticleModel state after the substance was changed, and expecting the model to be fully updated.  When the property notifications were shuffled such that things outside the model were notified of the substance change before the model had processed it, the state was inconsistent and caused assertions.  I implemented changes that made the handlers more independent, i.e. they no longer reach into the MultipleParticleModel instance for information, and this seems to have resolved the problem.

Once the problem that was causing the assertion was fixed, I noticed an issue with updates to the layout of the 2nd screen, so I fixed that as well.

@zepumph - You're welcome to review if you like, since you reported the problem initially.  I don't think it's absolutely necessary if you don't have time, in which case you can just close.

**Comment by zepumph** [comment] 2020-06-24 23:33
I only gave a brief scan, and didn't feel like it was worth the cost of me trying to understand the changes more intimately. Thank you for the excellent summary above. 

Before closing, would you mind commenting briefly on the what you think the quality of this change is. Like from 1 (waste of time) to 5 (super great). There are a lot of these `?shuffleListener` issues across the project, and it may be nice to get an understanding of how valuable this time spent is as we do more and more of them.

**Comment by jbphet** [comment] 2020-06-25 20:24
@zepumph asked:

> Before closing, would you mind commenting briefly on the what you think the quality of this change is...from 1 (waste of time) to 5 (super great)[?]

I'd put it at a 3 on this scale.  I wouldn't call it a total waste of time because the code was improved as a result.  The coupling between components was simplified, I did some renaming that will hopefully serve to make things more comprehensible, and the actions that occur are now a more direct result of what happens in the model.  On the other hand, the actual behavior of the sim was fine prior to these changes, and I spent about 2.5 hours on it, so it's a bit hard to feel like it was a big win given all the other things on my plate.  I suspect it will be a similar story for many of the other sims that are failing the `shuffleListeners` test.

Back to @zepumph to make sure that he sees this update, then the issue should be closed.

**Closed** 2020-06-25 20:25 UTC
